version: '3.5'

services:
  backend_app:
    build:
      context: ./
      dockerfile: backend.Dockerfile
    working_dir: /kiosk
    command: flask run
    environment:
      FLASK_ENV: development
    volumes:
      - ./backend:/kiosk
    ports:
      - 5000:5000

  frontend_app:
    build:
      context: ./
      dockerfile: frontend.Dockerfile
    working_dir: /kiosk/app
    command: npm start
    volumes:
      - ./frontend:/kiosk/app:delegated
      - ./frontend/package.json:/kiosk/package.json
      - ./frontend/package-lock.json:/kiosk/package-lock.json
      - notused:/kiosk/app/node_modules
    ports:
      - 1234:1234
      - 2345:2345

volumes:
  notused: